testwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('translate_text/', views.translate_text, name='translate_text'),
    path('logout/', views.logout_view, name='logout'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('upload_img/', views.upload_img, name='upload_img'),
]

app/models.py
from django.db import models

# Create your models here.
class TranslatedWords(models.Model):
	translate_from = models.CharField(max_length=12)
	translate_to = models.CharField(max_length=12)
	sourse_word = models.TextField()
	translated_word = models.TextField()

	def __str__(self):
		return 'Translated:%s, From:%s, To:%s, Ressult:%s' % (self.sourse_word, self.translate_from, 
			self.translate_to, self.translated_word)

app/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()

app/views.py
# -*- coding: utf-8 -*- 
# Created by Iliyaz Kazikhodzhaev
# Import Django core utils
from django.shortcuts import render, redirect
from django.contrib.auth import logout, authenticate, login as login_user
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.conf import settings
from django import forms

# Import base function and Classe
from .forms import UploadFileForm
from .utils import handle_uploaded_file

# Import model for save translated text
from .models import TranslatedWords

# Import translator backeg
from googletrans import Translator
translator = Translator()


# Translation language dict
TRANLATOR_LANGUAGES = {
	'Russian': 'ru',
	'English': 'en',
	'Uzbek': 'uz',
	'Turkish': 'tk',
}


# Upload any type file to media folder in project unlimited until 20MB
def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            if request.FILES['file'].size < int(settings.MAX_UPLOAD_MEDIA_SIZE):
                handle_uploaded_file(request.FILES['file'], request.FILES['file'].name)
                return HttpResponseRedirect('/')
            else:
                raise forms.ValidationError("only 20 MB photo and JPG, PNG is allowed")
    else:
        form = UploadFileForm()
    return render(request, 'profile.html', {'form': form})


# Upload just image and just 'JPG', 'PNG', 'jpg', 'png' types unlimited until 5MB
def upload_img(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            img_name = request.FILES['file'].name
            if request.FILES['file'].size < int(settings.MAX_UPLOAD_PHOTO_SIZE) and img_name.split('.')[1] in ['JPG', 'PNG', 'jpg', 'png']:
                save_path = 'images/'+img_name
                handle_uploaded_file(request.FILES['file'], save_path)
                return HttpResponseRedirect('/')
            else:
                raise forms.ValidationError("only 5 MB photo and JPG, PNG is allowed")
    return render(request, 'profile.html')


# Translate and save translated text in to database
def translate_text(request):
    if request.method == 'POST':
    	translate_content = request.POST.get('translate_content')
    	if translate_content == '':
    		return render(request, 'profile.html', {'translate_error': 'Pleas type the text!'})
    	translate_from = request.POST.get('translate_from')
    	translate_to = request.POST.get('translate_to')
    	trns = translator.translate(translate_content, dest=translate_to, src=translate_from)
    	TranslatedWords.objects.create(translate_from=translate_from,
    		translate_to=translate_to, sourse_word=translate_content, translated_word=trns.text)
    	return render(request, 'profile.html', {'translate_result': trns.text, 'translate_content': translate_content})
    else:
    	return render(request, 'profile.html', {'translate_error': 'Some think go wrong!'})


# log out end redirect login page
def logout_view(request):
    logout(request)
    return redirect('/')


''' check user authetification if user authenticated will open main page for transalte 
    and upload files else will return login page'''
def profile(request):
	if not request.user.is_authenticated:
		return redirect('/login')
	return render(request, 'profile.html')

	
# Login page for authetification
def login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login_user(request, user)
            return redirect('/')
        else:
            # Return a 'disabled account' error message
            return render(request, 'login.html', {'error': 'Pleas check username or password!'})
    else:
    	return render(request, 'login.html', {'error': 'Login error! Pleas check username and password'})
    return request(request, 'login.html')

templates/base.html
<!-- Base template for use every where -->
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<style type="text/css">
		body {
		    height: 100%;
		}

		.container {
		    height: 100%;
		    display: flex;
		    justify-content: center;
		    align-items: center;
		}
	</style>
</head>
<body>
{% block content %}

{% endblock %}
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</html>

templates/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}
<div class="col-md-3" style="margin: 10% 10% 20% 35%">
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
      <div class="form-group">
        <label for="exampleInputEmail1">Username</label>
        <input name="username" class="form-control" id="id_username" aria-describedby="emailHelp" placeholder="Enter username" name>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" name="password" class="form-control" id="id_password" placeholder="Password">
      </div>
      <input type="submit" class="btn btn-primary" value="login">
      <input type="hidden" name="next" value="{{ next }}">
    </form>
</div>

{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% block content %}
	<a href="{% url 'logout' %}">Logout</a>
	<div class="col-md-6" style="margin: 3% 0 0 25%">
		<form method="post" action="{% url 'translate_text' %}">
			{% csrf_token %}
			<label>Translate from: </label>
			<select class="form-control" name="translate_from">
			  <option>Russian</option>
			  <option>English</option>
			  <option>Uzbek</option>
			  <option>Turkish</option>
			</select>
			<label>To: </label>
			<select class="form-control" name="translate_to">
			  <option>Russian</option>
			  <option selected="selected">English</option>
			  <option>Uzbek</option>
			  <option>Turkish</option>
			</select>
			<p style="color: red">{{ translate_error }}</p>
			<label for="comment">Text for translate: </label>
	  		<textarea class="form-control" rows="5" name='translate_content'>{{ translate_content }}</textarea></br>
	  		<input type="submit" value="Translate" class="btn btn-primary">
		</form>
		{{ translate_result }}
	</div>
	<h1 style="text-align: center;"> Uplod content </h1>
	<div class="container">
	  	<div class="row">
	  		<div class="col-md-6">
				<form method="post" action="{% url 'upload_file' %}" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="custom-file">
						<p><label for="id_file">File:</label> <input name="file" required="" id="id_file" type="file"></p>
					  	<input type="submit" value="Upload file" class="btn btn-primary">
					</div>
				</form>
			</div>
			<div class="col-md-6" >
				<form method="post" action="{% url 'upload_img' %}" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="custom-file">
					  <p><label for="id_file">File:</label> <input name="file" required="" id="id_file" type="file"></p>
					  <input type="submit" value="Upload img" class="btn btn-primary">
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}